name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
      
      - name: Install Linux dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      
      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop
      
      - name: Install Flutter dependencies
        run: |
          flutter clean
          flutter pub get
      
      - name: Build Linux
        run: |
          flutter build linux || {
            echo "Build failed. Checking pub dependencies..."
            flutter pub deps
            exit 1
          }
      
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: build/linux/x64/release/bundle

  build-web:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
      
      - name: Install Flutter dependencies
        run: |
          flutter clean
          flutter pub get
      
      - name: Build Web
        run: |
          flutter build web || {
            echo "Build failed. Checking pub dependencies..."
            flutter pub deps
            exit 1
          }
      
      - name: Upload Web artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web

  create-release:
    needs: [build-linux, build-web]
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Linux build
        uses: actions/download-artifact@v3
        with:
          name: linux-build
          path: linux-build
      
      - name: Download Web build
        uses: actions/download-artifact@v3
        with:
          name: web-build
          path: web-build
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            linux-build/**/*
            web-build/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
